# Generated by Django 4.0.4 on 2022-09-21 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('caption', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.IntegerField(default=0)),
                ('video_post', models.FileField(default='null', upload_to='post_video/%y/%m/%d', verbose_name='video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=1000)),
                ('comment_on_post', models.UUIDField()),
                ('commented_date', models.DateTimeField(default=datetime.datetime(2022, 9, 21, 16, 28, 29, 267109))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='account.userinfo')),
            ],
        ),
    ]
