# Generated by Django 4.0.4 on 2022-07-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user_post',
            field=models.ImageField(upload_to='post_image/%y/%m/%d'),
        ),
    ]
