# Generated by Django 4.0.4 on 2022-07-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='followers',
            new_name='FollowerCount',
        ),
    ]
