# Generated by Django 4.0.4 on 2022-07-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_followers_followercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likePost',
        ),
    ]
