# Generated by Django 4.0.4 on 2022-07-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_likepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowerCount',
            new_name='FollowersCount',
        ),
    ]
